name: Generate Stats Images

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29  # v2.2.1 tag
      with:
        version: 0.15.2

    - name: Build
      run: |
        zig build --release

    - name: Checkout history branch
      run: |
        git config --global user.name "jstrieb/github-stats"
        git config --global user.email "github-stats[bot]@jstrieb.github.io"
        # Push generated files to the generated branch
        git pull
        git checkout generated || git checkout -b generated

    - name: Generate images
      run: |
        ./zig-out/bin/github-stats
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
        EXCLUDE_LANGS: "Perl,Python,PHP,JavaScript,HTML,CSS,C++,C,TeX,Perl 6,Elixir,XSLT,ShaderLab,C#,Roff"
        EXCLUDE_PRIVATE: "false"
        DEBUG: "false"
        # TODO: Remove this when they get their API working again
        # https://github.com/orgs/community/discussions/192970
        MAX_RETRIES: 5

    - name: Commit to the repo
      run: |
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push --set-upstream origin generated

    - name: Slack Notification (not success)
      uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
      if: "! success()"
      continue-on-error: true
      with:
        status: ${{ job.status }}
        webhook-url: ${{ secrets.SLACK_WEBHOOK }}
